/********************************************************************************
** Form generated from reading ui file 'ui_main_window.jui'
**
** Created: Fri Jul 27 09:42:53 2007
**      by: Qt User Interface Compiler version 4.3.0
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

package uk.ac.sanger.motifxplorer.ui;

import com.trolltech.qt.core.*;
import com.trolltech.qt.gui.*;

/*
 * I kept this in a distinct separate package as this class 
 * should be kept autogenerated by the 
 * (logical to keep this and the corresponding .jui resource file in a place
 * package from other UI stuff)
 */
public class UiMainWindow
{
    public QAction actionNew;
    public QAction actionSave;
    public QAction actionExport_PDF;
    public QAction actionOpen;
    public QAction actionClose;
    public QAction actionQuit;
    public QAction actionShift_left;
    public QAction actionShift_right;
    public QAction actionReverse_complement;
    public QAction actionBest_hits;
    public QAction actionBest_reciprocal_hits;
    public QAction actionClear_selection;
    public QWidget centralwidget;
    public QWidget verticalLayout;
    public QVBoxLayout vboxLayout;
    public QTableView motifTableView;
    public QMenuBar menubar;
    public QMenu menuMotifExplorer;
    public QMenu menuEdit;
    public QMenu menuAnalysis;
    public QStatusBar statusbar;

    public UiMainWindow() { super(); }

    public void setupUi(QMainWindow uiMainWindow)
    {
        uiMainWindow.setObjectName("UiMainWindow");
        uiMainWindow.resize(new QSize(800, 600).expandedTo(uiMainWindow.minimumSizeHint()));
        actionNew = new QAction(uiMainWindow);
        actionNew.setObjectName("actionNew");
        actionSave = new QAction(uiMainWindow);
        actionSave.setObjectName("actionSave");
        actionExport_PDF = new QAction(uiMainWindow);
        actionExport_PDF.setObjectName("actionExport_PDF");
        actionOpen = new QAction(uiMainWindow);
        actionOpen.setObjectName("actionOpen");
        actionClose = new QAction(uiMainWindow);
        actionClose.setObjectName("actionClose");
        actionQuit = new QAction(uiMainWindow);
        actionQuit.setObjectName("actionQuit");
        actionShift_left = new QAction(uiMainWindow);
        actionShift_left.setObjectName("actionShift_left");
        actionShift_right = new QAction(uiMainWindow);
        actionShift_right.setObjectName("actionShift_right");
        actionClear_selection = new QAction(uiMainWindow);
        actionClear_selection.setObjectName("actionClear_selection");
        actionReverse_complement = new QAction(uiMainWindow);
        actionReverse_complement.setObjectName("actionReverse_complement");
        actionBest_hits = new QAction(uiMainWindow);
        actionBest_hits.setObjectName("actionBest_hits");
        actionBest_reciprocal_hits = new QAction(uiMainWindow);
        actionBest_reciprocal_hits.setObjectName("actionBest_reciprocal_hits");
        centralwidget = new QWidget(uiMainWindow);
        centralwidget.setObjectName("centralwidget");
        verticalLayout = new QWidget(centralwidget);
        verticalLayout.setObjectName("verticalLayout");
        verticalLayout.setGeometry(new QRect(0, 0, 601, 421));
        QSizePolicy sizePolicy = new QSizePolicy(com.trolltech.qt.gui.QSizePolicy.Policy.Maximum, com.trolltech.qt.gui.QSizePolicy.Policy.Maximum);
        sizePolicy.setHorizontalStretch((byte)0);
        sizePolicy.setVerticalStretch((byte)0);
        sizePolicy.setHeightForWidth(verticalLayout.sizePolicy().hasHeightForWidth());
        verticalLayout.setSizePolicy(sizePolicy);
        verticalLayout.setAutoFillBackground(true);
        vboxLayout = new QVBoxLayout(verticalLayout);
        vboxLayout.setObjectName("vboxLayout");
        vboxLayout.setContentsMargins(0, 0, 0, 0);
        motifTableView = new QTableView(verticalLayout);
        motifTableView.setObjectName("motifTableView");
        motifTableView.setShowGrid(true);
        motifTableView.setGridStyle(com.trolltech.qt.core.Qt.PenStyle.SolidLine);
        motifTableView.setSortingEnabled(true);

        vboxLayout.addWidget(motifTableView);

        uiMainWindow.setCentralWidget(centralwidget);
        menubar = new QMenuBar(uiMainWindow);
        menubar.setObjectName("menubar");
        menubar.setGeometry(new QRect(0, 0, 800, 22));
        menuMotifExplorer = new QMenu(menubar);
        menuMotifExplorer.setObjectName("menuMotifExplorer");
        menuEdit = new QMenu(menubar);
        menuEdit.setObjectName("menuEdit");
        menuAnalysis = new QMenu(menubar);
        menuAnalysis.setObjectName("menuAnalysis");
        uiMainWindow.setMenuBar(menubar);
        statusbar = new QStatusBar(uiMainWindow);
        statusbar.setObjectName("statusbar");
        uiMainWindow.setStatusBar(statusbar);

        menubar.addAction(menuMotifExplorer.menuAction());
        menubar.addAction(menuEdit.menuAction());
        menubar.addAction(menuAnalysis.menuAction());
        menuMotifExplorer.addAction(actionNew);
        menuMotifExplorer.addAction(actionSave);
        menuMotifExplorer.addAction(actionExport_PDF);
        menuMotifExplorer.addAction(actionOpen);
        menuMotifExplorer.addAction(actionClose);
        menuMotifExplorer.addAction(actionQuit);
        menuEdit.addAction(actionShift_left);
        menuEdit.addAction(actionShift_right);
        menuEdit.addAction(actionReverse_complement);
        menuAnalysis.addAction(actionBest_hits);
        menuAnalysis.addAction(actionBest_reciprocal_hits);
        retranslateUi(uiMainWindow);
        actionSave.triggered.connect(actionSave, "trigger()");

        uiMainWindow.connectSlotsByName();
    } // setupUi

    void retranslateUi(QMainWindow UiMainWindow)
    {
        UiMainWindow.setWindowTitle("MotifXplorer");
        actionNew.setText("New");
        actionSave.setText("Save..");
        actionExport_PDF.setText("Export PDF..");
        actionOpen.setText("Open..");
        actionClose.setText("Close");
        actionQuit.setText("Quit");
        actionShift_left.setText("Shift left");
        actionShift_right.setText("Shift right");
        actionReverse_complement.setText("Reverse complement");
        actionBest_hits.setText("Best hits");
        actionBest_reciprocal_hits.setText("Best reciprocal hits");
        menuMotifExplorer.setTitle("File");
        menuEdit.setTitle("Edit");
        menuAnalysis.setTitle("Analysis");
    } // retranslateUi

}

